feat: add /cid/:cid to linkdex CARs by cid
web3-storage/linkdex-api pull request #6
Opened 2022-09-13 12:07 UTC by olizilla

Try and find a set of CARs that contain a complete DAG for a given CID.

For dotStorage CARs are grouped by userid with keys like `raw/<cid>/<userid>/<hash>.car`.

We find all the CARs for a given cid by prefix, group them by userid, and then sort by count of CARs, under the assumptions that the upload with the most CARs is likely to contain the full DAG.

License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>

2022-10-12 09:47 UTC, olizilla commented
This in hold as we don't currently need it. We have the `key` in the dotstroage worker, and after the last s3 upload of a set of partials, the final call as access to all the partial cars. We don't need a cron job to find it later, where we might only have the CID.

This may change if we move to a different s3 key structure.

2023-04-21 09:28 UTC, alanshaw requested changes

2023-04-21 09:28 UTC, alanshaw commented on services/functions/linkdex-cid.ts
> +  const prefix = `raw/${cid}/`
Not blocking, but we should consider CARs in `complete/${cid}`. For examples, CARs from [backup](https://github.com/web3-storage/backup/blob/main/index.js#L133) are written there.

2023-04-21 09:28 UTC, alanshaw commented on services/functions/linkdex-cid.ts
> +      return response({ structure: 'Complete' })
Shouldn't we return the full report here?

2023-04-21 15:11 UTC, alanshaw commented
https://github.com/web3-storage/linkdex-api/pull/11 addresses the two review comments so provided we can merge it here we should be good to go.

2023-04-24 16:30 UTC, alanshaw approved these changes

2023-04-24 17:16 UTC, merged